### ISSUE TITLE
Getting error with new release version

### ISSUE THREAD

**Issue by aprilb** [ianstormtaylor/to-constant-case#2]
My build is failing due to:
Error: no remote found for dependency "ianstormtaylor/to-constant-case@1.0.0". Visit http://component.github.io/troubleshooting for help.

`cogent "https://bitbucket.org/api/1.0/repositories/ianstormtaylor/to-constant-case/raw/v1.0.0/component.json" is not valid JSON +345ms`

Missing: component.json.

I will create one and PR: https://github.com/ianstormtaylor/to-constant-case/pull/3

**Comment by ianstormtaylor** [comment]
@aprilb thanks! I actually just dropped component support when bumping everything to `1.0.0`. If you want you can peg it at `~0.1.2` to get the older version that still has component support.
